name: Deployment

concurrency: production

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Check out manifests repo
        uses: actions/checkout@v4
        with:
          repository: ilopezluna/target
          persist-credentials: true # explicitly: needed later to commit + pull request
          path: manifests
      - name: Render docker image reference to manifests
        uses: mikefarah/yq@v4.44.2
        with:
          cmd: yq -n '.service.image.tag = strenv(GITHUB_RUN_NUMBER)' | tee manifests/root/components/example/image-values.yaml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          path: manifests
          commit-message: ${{ github.event.head_commit }}
          branch: ${{ github.event.head_commit.id }}