name: Deployment

concurrency: production

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Get latest commit link
        id: get_commit_link
        run: |
          REPO_URL="https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}"
          echo "Latest commit URL: $REPO_URL"
          echo "::set-output name=commit_url::$REPO_URL"

      - name: Check out manifests repo
        uses: actions/checkout@v4
        with:
          repository: ilopezluna/target
          persist-credentials: true # explicitly: needed later to commit + pull request
          path: manifests

      - name: Render docker image reference to manifests
        uses: mikefarah/yq@v4.44.2
        with:
          cmd: yq -n '.service.image.tag = strenv(GITHUB_RUN_NUMBER)' | tee manifests/root/components/example/image-values.yaml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT }}
          path: manifests
          title: Link to latest commit is ${{ steps.get_commit_link.outputs.commit_url }}
          branch: deploy-example-${{ github.run_number }}